version: '3'
services:
  azure-vote-back2:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: azure-vote-back2
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  azure-vote-front2:
    build: ./azure-vote
    image: mcr.microsoft.com/azuredocs/azure-vote-front2:v1
    container_name: azure-vote-front2
    environment:
      REDIS: azure-vote-back2
    ports:
        - "8080:80"
